# Reachy kinematics

In this notebook we will talk about kinematics!

As explained in other notebooks, usign ReachySDK you can change the joints positions if and only if the motors are in stiff mode. There are two ways to send a new target position: 

* **with goal_position**: when this attribute is set, the joint will try to reach the position it as fast as it can and it can be pretty fast (up to 700 degrees per second). You can lower the *speed_limit* but we don't recommend to use this method as it gets really hard to follow complex trajectories and have precise timing. Even though you can change the motor speed, you have no control over the acceleration.  


* **using goto()**: instead of playing with the goal_position you can use the *goto* method that is implemented in the SDK. This method generates a trajectory between the present position and the goal position. This trajectory is then interpolated at a predefined frequency (100Hz) to compute all intermediary target positions that should be followed before reaching the final goal position. Depending on the interpolation mode chosen, you can have a better control over speed and acceleration.

The two interpolation modes that we use consist in working either linearly or with the minjerk function.

<img src="https://raw.githubusercontent.com/pollen-robotics/reachy-sdk/notebooks_documentation/notebooks/images/kinematics/interpolation.png?token=AHZJ5IBL7QZHESYVASSGUEDAMG7FU" alt="drawing" width="500"/>

Both trajectories start and finish at the same point but don't follow the same intermediate positions.
The minimum jerk will slowly accelerate at the begining and slowly decelerate at the end. This makes the movements more natural, you'll see this below.

Now let's make our robot move! We will make the same arm movement but in three different ways, by setting the *goal_position* and using the *goto* method with each interpolation mode.

We will put Reachy's right arm in the right-angled position. First, place it on a table and make sure that there will be no obstacles along its way.

In [1]:
from reachy_sdk import ReachySDK

from reachy_sdk.trajectory.interpolation import InterpolationMode

In [2]:
reachy = ReachySDK(host='localhost')

In [3]:
# Reachy's right arm joints are joints 8 to 15
for joint in reachy.joints[8:16]:
    print(joint.name)

r_shoulder_pitch
r_shoulder_roll
r_arm_yaw
r_elbow_pitch
r_forearm_yaw
r_wrist_pitch
r_wrist_roll
r_gripper


### goal_position

First, we will use set the *goal_position* on each joint to put the right arm in a right-angled position. 

In [4]:
# Put the joints in stiff mode
for joint in reachy.joints[8:16]:
    joint.compliant = False

In [5]:
# Define what the goal_position of each joint will be
right_angle_position = {
    'r_shoulder_pitch': 0,
    'r_shoulder_roll': 0,
    'r_arm_yaw': 0,
    'r_elbow_pitch': -90,
    'r_forearm_yaw': 0,
    'r_wrist_pitch': 0,
    'r_wrist_roll': 0,
    'r_gripper': 0,
}

In [6]:
#Set each goal_position
from operator import attrgetter

for name, goal in zip(right_angle_position.keys(), right_angle_position.values()):
    joint = attrgetter(name)(reachy)
    joint.goal_position = goal

A bit too fast, isn't it? The problem with this is that you can't control the movement's speed.

Now we will put the joints back to compliant mode, so put your hand below the arm to prevent the arm from falling on the table.

In [7]:
for joint in reachy.joints[8:16]:
    joint.compliant = True

Next, let's play the same movement but using the *goto* method.

### goto with linear interpolation

In [13]:
# First put the joints of the right arm in stiff mode
for joint in reachy.joints[8:16]:
    joint.compliant = False

In [11]:
reachy.goto(
    {getattr(reachy, joint.name): gp for joint, gp in zip(reachy.joints[8:16], right_angle_position.values())},
duration=1.0,
interpolation_mode=InterpolationMode.LINEAR,
)

You can play with the duration parameter, the unit is in seconds.

In [12]:
# First put the joints of the right arm in stiff mode
for joint in reachy.joints[8:16]:
    joint.compliant = True

### goto with minjerk interpolation

In [59]:
# First put the joints of the right arm in stiff mode
for joint in reachy.joints[8:16]:
    joint.compliant = False

In [60]:
reachy.goto(
    {getattr(reachy, joint.name): gp for joint, gp in zip(reachy.joints[8:16], harder_pos.values())},
duration=1.0,
interpolation_mode=InterpolationMode.MINIMUM_JERK
)

In [21]:
for joint in reachy.joints[8:16]:
    joint.compliant = True

The use of goto has the advantage of easily giving control on the trajectory time. The difference between the two interpolation modes might not be huge on a simple movement like the on we just did, but on more complexe ones, the difference can be quite important. 

Like we said before, minjerk interpolation gives more natural movements. Try it yourself with custom movements!

You can try with the following goal position for example where Reachy places its right end-effector on its right hip.

In [15]:
hand_on_hip_pos = {
'r_shoulder_pitch': 16.726945447159054,
 'r_shoulder_roll': -66.43789209449601,
 'r_arm_yaw': 61.054944877528094,
 'r_elbow_pitch': -120.92307608487477,
 'r_forearm_yaw': -12.463343291751162,
 'r_wrist_pitch': -27.824175772826795,
 'r_wrist_roll': 41.20234435672571,
 'r_gripper': -25.073313669509574
}

## Arm coordinate system

### Joint coordinates

In all examples above, we have used what is called joint coordinates to move Reachy. This means that we have controlled each joint separately.

### Kinematic model

Controlling a robot in joint coordinates can be hard and is often far from what we actually do as humans. When we want to grasp an object in front of us, we think of where we should put our hand, not how to flex each individual muscle to reach this position. This approach relies on the cartesian coordinates: the 3D position and orientation in space.

Forward and Inverse Kinematics is a way to go from one coordinates system to the other:

* **forward kinematics: joint coordinates –> cartesian coordinates**
* **inverse kinematics: cartesian coordinates –> joint coordinates**

We have defined the whole kinematic model of the arm. This means the translation and rotation required to go from one joint to the next one. On a right arm equipped with a force gripper this actually look like this:

<img src="https://raw.githubusercontent.com/pollen-robotics/reachy-sdk/notebooks_documentation/notebooks/images/kinematics/right_arm_kinematic_model.png?token=AHZJ5IGJ7XNJFFZHHQTTZODAMHYQG" alt="drawing" width="300"/>

To use and understand the kinematic model, you need to know how Reachy coordinate system is defined (from Reachy's perspective), see below:

<img src="https://raw.githubusercontent.com/pollen-robotics/reachy-sdk/notebooks_documentation/notebooks/images/kinematics/arm_axis.png?token=AHZJ5ID66GQKUY3FBQ74GR3AMHNIU" alt="drawing" width="300"/>

* the X axis corresponds to the foward arrow.
* the Y axis corresponds to the right to left arrow.
* the Z axis corresponds to the up arrow.

The origin of this coordinate system is located in the upper part of the robot trunk. Basically, if you imagine a segment going from the left shoulder to the right shoulder of the robot, the origin is the middle of this segment.

The units used for this coordinate system are the meter. So the point (0.3, -0.2, 0) is 30cm in front of the origin, 20cm to the right and at the same height.

## Forward kinematics

Using the joint coordinates and the kinematic model defined above, we can compute the 3D position and orientation of the right or left end-effector with the *forward_kinematics* method.

We consider the end-effector to be in a virtual joint located in the gripper and referred as *'right_tip'* or *'left_tip'* in the [urdf file](https://github.com/pollen-robotics/reachy_kinematics/blob/master/reachy.URDF), as shown below. 

<img src="https://raw.githubusercontent.com/pollen-robotics/reachy-sdk/notebooks_documentation/notebooks/images/kinematics/eef.png" alt="drawing" width="200"/>

The red dot corresponds to the *'right_tip'*.

You can see the right and left end-effectors animated in the gif below.

<img src="https://raw.githubusercontent.com/pollen-robotics/reachy-sdk/notebooks_documentation/notebooks/images/safety/reachy_eef.gif" alt="drawing" width="300"/>

As explained, the forward kinematics allows to go from the joint coordinates system to the cartesian coordinates system. Both arms have their *forward_kinematics* method.

In [16]:
reachy.r_arm.forward_kinematics()

array([[ 0.06368817, -0.02263947, -0.99771302,  0.32420031],
       [ 0.07383961,  0.99710925, -0.01791228, -0.19942696],
       [ 0.99523441, -0.07252994,  0.06517575, -0.42596169],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

The 4x4 matrix returned by the *forward_kinematics* method is what is often called a pose. It actually encodes both the 3D translation (as a 3D vector) and the 3D rotation (as a 3x3 matrix) into one single representation. 

\begin{bmatrix}
R_{11} & R_{12} & R_{13} & T_{x} \\
R_{21} & R_{22} & R_{23} & T_{y} \\
R_{31} & R_{32} & R_{33} & T_{z} \\
0 & 0 & 0 & 1 \\
\end{bmatrix}

The instruction 

```python
reachy.r_arm.forward_kinematics()
```

returns the current pose of the right end-effector, based on the present position of every joint in the right arm. 

You can also compute the pose for a given joints position, to do that just pass the list of position as argument of *forward_kinematics*. Be careful to respect the order of the position you give.

For example, we can compute the forward kinematics for the right-angle position we used earlier.

In [17]:
reachy.r_arm.forward_kinematics(list(right_angle_position.values())[:-1])

array([[ 0.    ,  0.    , -1.    ,  0.3675],
       [ 0.    ,  1.    ,  0.    , -0.202 ],
       [ 1.    ,  0.    ,  0.    , -0.28  ],
       [ 0.    ,  0.    ,  0.    ,  1.    ]])

With this result, we can tell that when the right arm is in the right angle position, the right end-effector is 37cm in front of the origin, 20cm to the left and 28cm below the origin.

As of the rotation matrix, the identity matrix corresponds to the zero position of the robot

\begin{bmatrix}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1\\
\end{bmatrix}

which is when the hand is facing toward the bottom.

Here we obtained the rotation matrix

\begin{bmatrix}
0 & 0 & -1\\
0 & 1 & 0\\
1 & 0 & 0\\
\end{bmatrix}

We can use scipy to understand what this matrix represents.

In [44]:
from scipy.spatial.transform import Rotation as R
import numpy as np

In [41]:
R.from_matrix([
    [0, 0, -1],
    [0, 1, 0],
    [1, 0, 0],
]).as_euler('xyz', degrees=True)

array([  0., -90.,   0.])

So scipy tells us that a rotation of -90° along the *y* axis has been made to get this matrix, which is coherent with the result because having the hand facing forward corresponds to this rotation according to Reachy's *xyz* axis that we saw above.

## Inverse kinematics

Knowing where you arm is located in the 3D space can be useful but most of the time what you want is to move the arm in cartesian coordinates. You want to have the possibility to say: “move your hand to [x, y, z] with a 90° rotation around the Y axis”.

This is what inverse kinematics does. We have provided a method to help you with that. You need to give it a 4x4 target pose, like the one given by the forward kinematics, and an initial joint state.

To make this more concrete, let's first try with a simple example. We will make the hand of the robot going from a point A to a point B in 3D space. You always have to provide poses to the inverse kinematics that are actually reachable by the robot.

For our starting point, let's imagine a point in front of the robot right shoulder and slightly below. With Reachy coordinate system, we can define such a point with the following coordinates:

\begin{equation} A =
\begin{pmatrix}
0.3 & -0.2 & -0.3
\end{pmatrix}
\end{equation}

For our end point we will stay in a parallel plan in front of the robot (we keep the same x) and move to the upper left (20cm up and 20cm left). This gives us a B point such that:

\begin{equation} B =
\begin{pmatrix}
0.3 & 0.0 & -0.1
\end{pmatrix}
\end{equation}

But having the 3D position is not enough to design a pose. You also need to provide the 3D orientation via a rotation matrix. The rotation matrix is often the tricky part when building a target pose matrix.

Keep in mind that the identity rotation matrix corresponds to the zero position of the robot which is when the hand is facing toward the bottom. So if we want the hand facing forward when going from A to B, we need to rotate it from -90° around the y axis, as we saw in the forward kinematics part.

We know from before which rotation matrix corresponds to this rotation, but we can use scipy again to generate the rotation matrix for given rotations.

In [48]:
print(np.around(R.from_euler('y', np.deg2rad(-90)).as_matrix(), 3))

[[ 0. -0. -1.]
 [ 0.  1. -0.]
 [ 1.  0.  0.]]


We got the rotation matrix that we expected! 

As mentionned, building the pose matrix can be hard, so don't hesitate to use scipy to build your rotation matrix. You can also move the arm with your hand where you want it to be and use the forward kinematics to get an approximation of the target pose matrix you would give to the inverse kinematics.

Here, having the rotation matrix and the 3D positions for our points A and B, we can build both target pose matrices. 

In [51]:
A = np.array([
  [0, 0, -1, 0.3],
  [0, 1, 0, -0.2],  
  [1, 0, 0, -0.3],
  [0, 0, 0, 1],  
])

B = np.array([
  [0, 0, -1, 0.3],
  [0, 1, 0, 0],  
  [1, 0, 0, -0.1],
  [0, 0, 0, 1],  
])

*inverse_kinematics()* takes one optional argument, *q0*, which is the starting point of the inverse kinematics computation. If no *q0* is given, *q0* is considered to be equal to the present joints position.

Inverse kinematics is a really powerful way to define motions in coordinate systems that fits better with the defintion of many tasks (grasp the bottle in (x, y, z) for instance). Yet, this approach has also some important limitations.

It's important to understand that while the forward kinematics has a unique and well defined solution, the inverse kinematics is a much harder and ill defined problem. A Right Arm with a Gripper has 8 Degrees Of Freedom (8 motors) meaning that you may have multiple solutions to reach the same 3D point in space.

Because the inverse kinematics algorithm used is based on optimisation techniques, giving a starting point *q0* may have a tremendous influence on the final result.

Now let's use the inverse kinematics to move between our two points A and B! We will consider that the starting point is the right angled position that we used before, then the arm will go to A and finish at B. 

In [61]:
joint_pos_A = reachy.r_arm.inverse_kinematics(A, q0=np.deg2rad(list(right_angle_position.values())[:-1]))

In [76]:
joint_pos_B = reachy.r_arm.inverse_kinematics(B, q0=np.deg2rad(list(right_angle_position.values())[:-1]))

In [77]:
# put the joints in stiff mode
for j in reachy.joints[8:16]:
    j.compliant = False

In [73]:
# use the goto function
reachy.goto({getattr(reachy,j.name): pos for j,pos in zip(reachy.joints[8:16], joint_pos_A)}, duration=2.0)

In [78]:
reachy.goto({getattr(reachy,j.name): pos for j,pos in zip(reachy.joints[8:16], joint_pos_B)}, duration=2.0)

In [79]:
# put the joints back to compliant mode
# don't forget to put your hand below the arm to prevent it from falling hard!
for j in reachy.joints[8:16]:
    j.compliant = True

That's it! Now you know everything on Reachy's kinematics!